ktor {
    deployment {
        port = 8000
        port = ${?PORT}
        connectionGroupSize = 2
        workerGroupSize = 5
        callGroupSize = 10
        shutdownGracePeriod = 2000
        shutdownTimeout = 3000
    }
    application {
        modules = [ com.allocator.ApplicationKt.module ]
    }
}
